// <auto-generated />
namespace IAWeb.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v_101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_101));
        
        string IMigrationMetadata.Id
        {
            get { return "201707211805384_v_1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
