// <auto-generated />
namespace IAWeb.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v_104 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_104));
        
        string IMigrationMetadata.Id
        {
            get { return "201712031709100_v_1.0.4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
